name: Lint
on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Luacheck Linter
        uses: judaew/luacheck-action@v0.2.2
        with:
          targets: "."
          args: "-g"
